### ISSUE TITLE
名前空間版のバージョンについて

### ISSUE THREAD

**Issue by DQNEO** [dietcake/dietcake#33]
commit https://github.com/dietcake/dietcake/commit/2b4bcf97892978516343757dee90dd9e80bd1037 に対して、あらたに `v1.2.0` のタグを打っていただきたいです。(v2.0.0のタグはそのままで大丈夫です)

そうすれば、
* v1.1.2 名前空間なし
* v1.2.0 名前空間付きが入った(名前空間なしもそのまま使える)
* v2.0.0  v1.2.0と中身は同じだが、名前空間なしクラスが残ってるのは消し忘れなので使わないでという扱い。
* v.2.1.0 名前空間なしのクラスを削除 (←これからやる)

という風にできます。

**Comment by DQNEO** [comment]
v2は互換性捨てる意思表示なのかと思ってました(誤解してたかも..)。
そうではなくてv2で互換性維持するとしたら,下記プランでも大丈夫です！

# 修正案

* v1.1.2 名前空間なし
* v2.0.0 名前空間付きが入った

↑ここまでは既成事実

↓ここからが将来案

* v2.1.0 名前空間なしのクラスがDEPRECATED扱い、プラスその他の変更(PSR2等)
* v3.0.0 名前空間なしのクラスが消える。プラス他にも何か切り捨てる(PHP5.3とか)

**Comment by ha1t** [comment]
> v2は互換性捨てる意思表示なのかと思ってました(誤解してたかも..)。

たしかに一般的なフレームワークだとメジャーバージョンあがると変わりますもんね。
今回はバグの修正にとどまらない大きな変更があったのでバージョンをあげました。

フレームワークのバージョンがあがることで、その対応のためにアプリ側がコストをさいたり、
コストがさけなくて古いまま使って最新においてかれたり、
独自改変して使うみたいな事にはなってほしくないので、なるべく互換性は維持したいんですよね。

**Comment by DQNEO** [comment]
方針理解しました
回答ありがとうございますmm

**Comment by DQNEO** [comment]
結論：メジャーバージョンをあげてもなるべく互換性維持
